Added metadata definition for chat.postMessage and history
jolicode/slack-php-api pull request #156
Opened 2023-05-29 13:08 UTC by tchapuis

The Slack documentation says that we can include metadata in `chat.postMessage` arguments. See : https://api.slack.com/metadata

OpenApi spec for this argument doesn't seem to be up to date.

So I added it to the patched version for message definition and `chat.postMessage` method. I also added the `include_all_metadata` argument for the `conversations.history` method

2023-10-31 14:47 UTC, yngc0der commented
The temporary solution is create a custom endpoint class, and use this class to call api method:

```php
<?php

use JoliCode\Slack\Api\Endpoint\ChatPostMessage;

final class FixedChatPostMessageEndpoint extends ChatPostMessage
{
    protected function getFormOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getFormOptionsResolver();
        $optionsResolver->setDefined(['metadata']);
        $optionsResolver->setAllowedTypes('metadata', ['string']);
        return $optionsResolver;
    }
}


$slack->executeEndpoint(new FixedChatPostMessageEndpoint([
    'channel' => $channel,
    'text' => $text,
    'metadata' => $metadata,
]));
```

2023-10-31 15:42 UTC, damienalexandre requested changes
Hello, sorry for the very long delay on the review.

I fear the ".patch" file is wrong, it includes A LOT of changes that have nothing to do with the metadata definition :thinking: Maybe it's just because Slack updated their definition, but we should then split this in two PR.

Thank you for your understanding :pray:

2023-10-31 15:42 UTC, damienalexandre commented on resources/slack-openapi-sorted.patch
> +\ No newline at end of file
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**💭 thought:** ‏I think this should not appear in the patch file :thinking:

2023-11-10 09:18 UTC, tchapuis commented
Hello,
The patch file was a pain to get it right 😅

2023-11-10 10:09 UTC, damienalexandre commented
Thanks for working on this!

Tests on `main` were red, so I fixed them in https://github.com/jolicode/slack-php-api/pull/162 ;
could you please:

- rm -rf generated/
- vendor/bin/jane-openapi generate --config-file=.jane-openapi.php

And push?

2023-11-10 12:02 UTC, merged

2023-11-10 12:02 UTC, damienalexandre commented
Awesome, thank you so much!

2023-11-10 12:05 UTC, damienalexandre commented
Version v4.6.0 is published!