October 2020 api spec update
jolicode/slack-php-api pull request #96
Opened 2020-10-21 09:05 UTC by xavierlacot

* **Breaking** Specification update to latest Slack official version - see slackapi/slack-api-specs#44
  * add some new methods
  * remove all `im*`, `mpim*`, `channels*` and `groups*` channels
* re-generated the SDK files
* fixed tests to use the new generic `conversation*` methods
* ease up the patching process:
  * in the patched json file, sort endpoint query parameters by their `name` attributes, to keep a consistent order
  * auto-merge `objs_user` and `objs_conversation` polymorphic properties in order to keep the patch chunks as small as possible
* added some explanations in the "Updating the SDK" readme

2020-10-22 14:48 UTC, damienalexandre requested changes
Thanks for this massive work.

I still have to test it live but here is some preliminary comments:

- The Client has a new namespace: `\JoliCode\Slack\Api\Runtime\Client\Client`, does that change anything in the lib usage/documentation? Todo: check https://github.com/jolicode/slack-php-api/blob/master/src/ClientFactory.php
- Let's try to list the new Endpoints
- The new `callstack` property looks like a debug property from internal code at Slack, maybe we could remote it?

2020-10-22 14:48 UTC, damienalexandre commented on generated/Endpoint/ConversationsMark.php
> +        $optionsResolver->setAllowedTypes('ts', ['float']);
`ts` are usually typed as string, let's dive into that change.

2020-11-17 15:10 UTC, xavierlacot commented
> The Client has a new namespace: `\JoliCode\Slack\Api\Runtime\Client\Client`

Nope, the client is still the same class like before: [`\JoliCode\Slack\Api\Client`](https://github.com/jolicode/slack-php-api/blob/feature/api-update/generated/Client.php), it simply _extends_  `\JoliCode\Slack\Api\Runtime\Client\Client`

> Let's try to list the new Endpoints

Here we go :smiley: Below, the list of the endpoint changes introduced since the last version:

| **change** | **path** | **description** | **class** |
|-|-|-|-|
| - | `/admin.apps.approve` | Approve an app for installation on a workspace. | `JoliCode\Slack\Api\Endpoint\AdminAppsApprove` |
| - | `/admin.apps.approved.list` | List approved apps for an org or workspace. | `JoliCode\Slack\Api\Endpoint\AdminAppsApprovedList` |
| - | `/admin.apps.requests.list` | List app requests for a team/workspace. | `JoliCode\Slack\Api\Endpoint\AdminAppsRequestsList` |
| - | `/admin.apps.restrict` | Restrict an app for installation on a workspace. | `JoliCode\Slack\Api\Endpoint\AdminAppsRestrict` |
| - | `/admin.apps.restricted.list` | List restricted apps for an org or workspace. | `JoliCode\Slack\Api\Endpoint\AdminAppsRestrictedList` |
| added | `/admin.conversations.archive` | Archive a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsArchive` |
| added | `/admin.conversations.convertToPrivate` | Convert a public channel to a private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsConvertToPrivate` |
| added | `/admin.conversations.create` | Create a public or private channel-based conversation. | `JoliCode\Slack\Api\Endpoint\AdminConversationsCreate` |
| added | `/admin.conversations.delete` | Delete a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsDelete` |
| added | `/admin.conversations.disconnectShared` | Disconnect a connected channel from one or more workspaces. | `JoliCode\Slack\Api\Endpoint\AdminConversationsDisconnectShared` |
| added | `/admin.conversations.ekm.listOriginalConnectedChannelInfo` | List all disconnected channels—i.e., channels that were once connected to other workspaces and then disconnected—and the corresponding original channel IDs for key revocation with EKM. | `JoliCode\Slack\Api\Endpoint\AdminConversationsEkmListOriginalConnectedChannelInfo` |
| added | `/admin.conversations.getConversationPrefs` | Get conversation preferences for a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsGetConversationPrefs` |
| added | `/admin.conversations.getTeams` | Get all the workspaces a given public or private channel is connected to within this Enterprise org. | `JoliCode\Slack\Api\Endpoint\AdminConversationsGetTeams` |
| added | `/admin.conversations.invite` | Invite a user to a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsInvite` |
| added | `/admin.conversations.rename` | Rename a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsRename` |
| added | `/admin.conversations.restrictAccess.addGroup` | Add an allowlist of IDP groups for accessing a channel | `JoliCode\Slack\Api\Endpoint\AdminConversationsRestrictAccessAddGroup` |
| added | `/admin.conversations.restrictAccess.listGroups` | List all IDP Groups linked to a channel | `JoliCode\Slack\Api\Endpoint\AdminConversationsRestrictAccessListGroups` |
| added | `/admin.conversations.restrictAccess.removeGroup` | Remove a linked IDP group linked from a private channel | `JoliCode\Slack\Api\Endpoint\AdminConversationsRestrictAccessRemoveGroup` |
| added | `/admin.conversations.search` | Search for public or private channels in an Enterprise organization. | `JoliCode\Slack\Api\Endpoint\AdminConversationsSearch` |
| added | `/admin.conversations.setConversationPrefs` | Set the posting permissions for a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsSetConversationPrefs` |
| - | `/admin.conversations.setTeams` | Set the workspaces in an Enterprise grid org that connect to a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsSetTeams` |
| added | `/admin.conversations.unarchive` | Unarchive a public or private channel. | `JoliCode\Slack\Api\Endpoint\AdminConversationsUnarchive` |
| - | `/admin.emoji.add` | Add an emoji. | `JoliCode\Slack\Api\Endpoint\AdminEmojiAdd` |
| - | `/admin.emoji.addAlias` | Add an emoji alias. | `JoliCode\Slack\Api\Endpoint\AdminEmojiAddAlias` |
| - | `/admin.emoji.list` | List emoji for an Enterprise Grid organization. | `JoliCode\Slack\Api\Endpoint\AdminEmojiList` |
| - | `/admin.emoji.remove` | Remove an emoji across an Enterprise Grid organization | `JoliCode\Slack\Api\Endpoint\AdminEmojiRemove` |
| - | `/admin.emoji.rename` | Rename an emoji. | `JoliCode\Slack\Api\Endpoint\AdminEmojiRename` |
| - | `/admin.inviteRequests.approve` | Approve a workspace invite request. | `JoliCode\Slack\Api\Endpoint\AdminInviteRequestsApprove` |
| - | `/admin.inviteRequests.approved.list` | List all approved workspace invite requests. | `JoliCode\Slack\Api\Endpoint\AdminInviteRequestsApprovedList` |
| - | `/admin.inviteRequests.denied.list` | List all denied workspace invite requests. | `JoliCode\Slack\Api\Endpoint\AdminInviteRequestsDeniedList` |
| - | `/admin.inviteRequests.deny` | Deny a workspace invite request. | `JoliCode\Slack\Api\Endpoint\AdminInviteRequestsDeny` |
| - | `/admin.inviteRequests.list` | List all pending workspace invite requests. | `JoliCode\Slack\Api\Endpoint\AdminInviteRequestsList` |
| - | `/admin.teams.admins.list` | List all of the admins on a given workspace. | `JoliCode\Slack\Api\Endpoint\AdminTeamsAdminsList` |
| - | `/admin.teams.create` | Create an Enterprise team. | `JoliCode\Slack\Api\Endpoint\AdminTeamsCreate` |
| - | `/admin.teams.list` | List all teams on an Enterprise organization | `JoliCode\Slack\Api\Endpoint\AdminTeamsList` |
| - | `/admin.teams.owners.list` | List all of the owners on a given workspace. | `JoliCode\Slack\Api\Endpoint\AdminTeamsOwnersList` |
| - | `/admin.teams.settings.info` | Fetch information about settings in a workspace | `JoliCode\Slack\Api\Endpoint\AdminTeamsSettingsInfo` |
| - | `/admin.teams.settings.setDefaultChannels` | Set the default channels of a workspace. | `JoliCode\Slack\Api\Endpoint\AdminTeamsSettingsSetDefaultChannels` |
| - | `/admin.teams.settings.setDescription` | Set the description of a given workspace. | `JoliCode\Slack\Api\Endpoint\AdminTeamsSettingsSetDescription` |
| - | `/admin.teams.settings.setDiscoverability` | An API method that allows admins to set the discoverability of a given workspace | `JoliCode\Slack\Api\Endpoint\AdminTeamsSettingsSetDiscoverability` |
| - | `/admin.teams.settings.setIcon` | Sets the icon of a workspace. | `JoliCode\Slack\Api\Endpoint\AdminTeamsSettingsSetIcon` |
| - | `/admin.teams.settings.setName` | Set the name of a given workspace. | `JoliCode\Slack\Api\Endpoint\AdminTeamsSettingsSetName` |
| added | `/admin.usergroups.addChannels` | Add one or more default channels to an IDP group. | `JoliCode\Slack\Api\Endpoint\AdminUsergroupsAddChannels` |
| added | `/admin.usergroups.addTeams` | Associate one or more default workspaces with an organization-wide IDP group. | `JoliCode\Slack\Api\Endpoint\AdminUsergroupsAddTeams` |
| added | `/admin.usergroups.listChannels` | List the channels linked to an org-level IDP group (user group). | `JoliCode\Slack\Api\Endpoint\AdminUsergroupsListChannels` |
| added | `/admin.usergroups.removeChannels` | Remove one or more default channels from an org-level IDP group (user group). | `JoliCode\Slack\Api\Endpoint\AdminUsergroupsRemoveChannels` |
| - | `/admin.users.assign` | Add an Enterprise user to a workspace. | `JoliCode\Slack\Api\Endpoint\AdminUsersAssign` |
| - | `/admin.users.invite` | Invite a user to a workspace. | `JoliCode\Slack\Api\Endpoint\AdminUsersInvite` |
| - | `/admin.users.list` | List users on a workspace | `JoliCode\Slack\Api\Endpoint\AdminUsersList` |
| - | `/admin.users. [...]

2020-11-22 18:06 UTC, damienalexandre commented
Let's merge like this, I will try to test https://github.com/jolicode/slack-php-api/pull/96#discussion_r510188600 in another PR.

This is gonna be released later as a new major version. Thanks a lot @xavierlacot ! :tada:

2020-11-22 18:06 UTC, merged